### ISSUE TITLE
Why is the network output channel two

### ISSUE THREAD

**Issue by wangni-bupt** [Sachini/ronin#33]
After reading the paper, I wanted to try to run the code, but in practice, I found that the posture finally obtained was not 6 degrees of freedom.

The output channel of Position Network is 2, but I want to know whether it can output three degrees of freedom, namely X, y and Z.

The output channel of Heading Network is 2, but I don't understand the sin and cos explained in the paper, could you please interpret it? Meanwhile, I also want to know whether three degrees of freedom can be output.

**Comment by Sachini** [comment]
We don't have 6DoF pose ground truth as our data comes from two different devices which are not rigidly attached to each other. A device that records ground-truth pose is rigidly attached to the body.  Therefore we estimate the trajectory of a body instead of the IMU phone.

For heading, I'd refer you to the [ICRA paper](https://ieeexplore.ieee.org/abstract/document/9196860), which has the mathematical formulas
