### ISSUE TITLE
Understanding use of pretrained models

### ISSUE THREAD

**Issue by brentgti** [Sachini/ronin#44]
Hi @Sachini,

I am trying to use RoNIN to deduce location where GNSS satellite signals are poor or unavailable (like in urban canyons, not indoors). What I want to be able to do is deduce location when starting from a known location (where GNSS signal is available) and moving to where location can't be determined using GNSS.

I've read other posts (including #20, #25, and #41) here about using the pretrained models. I've gotten IMU data from an Android device using the app you provided and was able to run compile_dataset_h5.py to generate data.hdf5 and info.json files with the `--unannotated` switch, but the info.json file seems to be incomplete, compared to the info.json files I see in the datasets you provide. 

When I try to run ronin_resnet.py, I get `KeyError: 'gyro_integration_error'` in select_orientation_source in data_utils.py. I assume that this is because I'm not properly incorporating data from the game rotation vector (grv), but I don't understand how to do that. Can you provide more guidance on that? Thanks in advance.

**Comment by Sachini** [comment]
The error is because the value is missing in the `info.json` file generated. Please follow #25 and assign identity values to missing fields.  (We have not done so in the script to avoid confusion with correctly computed values) 
To always use game rotation vector in dataset you can set the grv_only flag when loading the dataset. This is automatically done in the script during testing (e.g. [here](https://github.com/Sachini/ronin/blob/805b7f0f28bb164ce89ada9ac05a9470dbe3d715/source/ronin_resnet.py#L76))
